name: ${PROJECT_NAME:-retro_hotel}

services:
  arcturus:
    image: ${IMAGE_REPOSITORY:?Set IMAGE_REPOSITORY}/${IMAGE_NAME_PREFIX:-tjanoekhotel}-arcturus:${IMAGE_TAG:-latest}
    build:
      context: ./vendor/nitro-docker/arcturus

  nitro:
    image: ${IMAGE_REPOSITORY:?Set IMAGE_REPOSITORY}/${IMAGE_NAME_PREFIX:-tjanoekhotel}-nitro:${IMAGE_TAG:-latest}
    build:
      context: ./vendor/nitro-docker/nitro

  imager:
    image: ${IMAGE_REPOSITORY:?Set IMAGE_REPOSITORY}/${IMAGE_NAME_PREFIX:-tjanoekhotel}-imager:${IMAGE_TAG:-latest}
    build:
      context: ./vendor/nitro-docker/imager

  cms:
    image: ${IMAGE_REPOSITORY:?Set IMAGE_REPOSITORY}/${IMAGE_NAME_PREFIX:-tjanoekhotel}-cms:${IMAGE_TAG:-latest}
    build:
      context: ./vendor/nitro-docker/atomcms
