name: ${PROJECT_NAME:-retro_hotel}

services:
  arcturus:
    image: ${IMAGE_REPOSITORY:?Set IMAGE_REPOSITORY}/${IMAGE_NAME_PREFIX:-tjanoekhotel}-arcturus:${IMAGE_TAG:-latest}
    build:
      context: ./vendor/nitro-docker
      dockerfile: ../../docker/arcturus.Dockerfile

  nitro:
    image: ${IMAGE_REPOSITORY:?Set IMAGE_REPOSITORY}/${IMAGE_NAME_PREFIX:-tjanoekhotel}-nitro:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: docker/nitro.Dockerfile

  assets:
    image: ${IMAGE_REPOSITORY:?Set IMAGE_REPOSITORY}/${IMAGE_NAME_PREFIX:-tjanoekhotel}-assets:${IMAGE_TAG:-latest}
    build:
      context: ./vendor/nitro-docker
      dockerfile: ../../docker/assets.Dockerfile

  imager:
    image: ${IMAGE_REPOSITORY:?Set IMAGE_REPOSITORY}/${IMAGE_NAME_PREFIX:-tjanoekhotel}-imager:${IMAGE_TAG:-latest}
    build:
      context: ./vendor/nitro-docker
      dockerfile: ../../docker/imager.Dockerfile

  cms:
    image: ${IMAGE_REPOSITORY:?Set IMAGE_REPOSITORY}/${IMAGE_NAME_PREFIX:-tjanoekhotel}-cms:${IMAGE_TAG:-latest}
    build:
      context: ./vendor/nitro-docker/atomcms
      dockerfile: ../../../docker/cms.Dockerfile

  proxy:
    image: ${IMAGE_REPOSITORY:?Set IMAGE_REPOSITORY}/${IMAGE_NAME_PREFIX:-tjanoekhotel}-proxy:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: docker/proxy.Dockerfile
